#!/usr/bin/env python3
"""Build the collaborator report DOCX from research-narrative.md via Pandoc.

Inputs (checked in / regenerated locally):
  - research-narrative.md   polished prose (source of truth for text)
  - figures/figure{1..7}_*.png   regenerated by generate_figures.py
  - styles-reference.docx   Word styles only (optional but recommended)

Does not read experiment summaries directly; run generate_figures.py first
(or use bin/build-collaborator-report).
"""
from __future__ import annotations

import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "research-narrative.md"
REFERENCE = ROOT / "styles-reference.docx"
BUILD_DIR = ROOT / "build"
OUTPUT = ROOT / "collaborator-report-v3.docx"
BUILD_COPY = BUILD_DIR / "collaborator-report-v3.docx"

REQUIRED_FIGURES = [
    "figures/figure1_article_recall.png",
    "figures/figure2_source_intervention.png",
    "figures/figure3_generalization.png",
    "figures/figure4_selection_ablation.png",
    "figures/figure5_dose_response.png",
    "figures/figure6_dual_lock.png",
    "figures/figure7_causal_tetrad.png",
    "figures/figure8_selective_force_native.png",
]


def build() -> Path:
    if not SOURCE.exists():
        raise FileNotFoundError(SOURCE)
    missing = [rel for rel in REQUIRED_FIGURES if not (ROOT / rel).exists()]
    if missing:
        print("Missing figures (run generate_figures.py first):", file=sys.stderr)
        for rel in missing:
            print(f"  - {rel}", file=sys.stderr)
        raise SystemExit(1)

    BUILD_DIR.mkdir(exist_ok=True)
    cmd = [
        "pandoc",
        str(SOURCE),
        "--from",
        "markdown+tex_math_single_backslash+tex_math_dollars",
        "--to",
        "docx",
        "--resource-path",
        str(ROOT),
        "-o",
        str(OUTPUT),
    ]
    if REFERENCE.exists():
        cmd.extend(["--reference-doc", str(REFERENCE)])
    else:
        print(
            f"WARNING: {REFERENCE.name} not found; using Pandoc default styles.",
            file=sys.stderr,
        )
    subprocess.run(cmd, check=True, cwd=ROOT)
    shutil.copy2(OUTPUT, BUILD_COPY)

    with zipfile.ZipFile(OUTPUT) as zf:
        xml = zf.read("word/document.xml").decode("utf-8", errors="ignore")
        media = [n for n in zf.namelist() if n.startswith("word/media/")]
    has_omath = "<m:oMath" in xml or "<m:oMathPara" in xml
    raw_dollars = "$$" in xml
    print(OUTPUT)
    print(f"oMath_present={has_omath} raw_dollar_delimiters={raw_dollars}")
    print(f"embedded_media_files={len(media)}")
    if not has_omath:
        print(
            "WARNING: no Word math tags found; equations may be plain text. "
            "Check Pandoc/math setup.",
            file=sys.stderr,
        )
    if len(media) < 8:
        print(
            f"WARNING: expected ≥8 embedded media files, found {len(media)}.",
            file=sys.stderr,
        )
    return OUTPUT


if __name__ == "__main__":
    build()
