project:
  output-dir: dist/iclr-camera-ready

format:
  pdf:
    keep-tex: true
    pdf-engine: latexmk
    documentclass: article
    biblio-style: iclr2027conference
    include-in-header:
      - _extensions/iclr/header-camera-ready.tex

params:
  target: iclr
  mode: camera-ready
  anonymous: false
