project:
  output-dir: dist/neurips-camera-ready

format:
  pdf:
    keep-tex: true
    pdf-engine: latexmk
    documentclass: article
    include-in-header:
      - _extensions/neurips/header-camera-ready.tex
    include-after-body:
      - _extensions/neurips/checklist.tex

params:
  target: neurips
  mode: camera-ready
  anonymous: false
