project:
  output-dir: dist/neurips-submission

format:
  pdf:
    keep-tex: true
    pdf-engine: latexmk
    documentclass: article
    include-in-header:
      - _extensions/neurips/header-submission.tex
    include-after-body:
      - _extensions/neurips/checklist.tex

params:
  target: neurips
  mode: submission
  anonymous: true
